name: Example workflow for Python using CloudDefense 
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run CloudDefense to check for vulnerabilities
      uses: cdefense/actions@v1.1
      with:
        project-name: TestCICD
        api-key:  ${{ secrets.OLD_CONSOLE}}
