name: Example workflow using CloudDefense
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run Cloud Defense to check for vulnerabilities
      uses: cdefense/actions/python@master
      with:
        project-name: Python_Github_Action_Test_1
        api-key: ${{ secrets.OLD_CONSOLE }}
